---
title: "BABS Learning and Memory Summary"
author: "JLC"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
---

# Learning and Memory Measures: BABS Neuropsych Battery

```{r setup, warning=FALSE, message=FALSE}
rm(list=ls())

# Packages
library(knitr); library(kableExtra); library(RColorBrewer); library(correlation); library(see); library(readxl); library(psych); library(tidyverse)

#Create data directories
NP.path<-"/Volumes/berry-lab/berry-lab/Brandeis_Aging_Brain_Study/BABS Data/Analysis/BABS NP MASTER.xlsx"
sess.path <-"/Volumes/berry-lab/berry-lab/Brandeis_Aging_Brain_Study/BABS Data/"

#Make data frames for neuropsych battery items from excel spreadsheet
BABS.NP.sess1 <- read_xlsx(NP.path, sheet = "Session 1")
```

## California Verbal Learning Test (CVLT)

```{r CVLT, warning=FALSE, message=FALSE}
d.CVLT <- BABS.NP.sess1 %>% select(BABS_ID, `AGE AT SESSION`, starts_with("CVLT")) %>%
                                          distinct(BABS_ID, .keep_all = T) %>%
  mutate_at(vars(starts_with("CVLT")), as.numeric)
#counting the number of observations and summarizing mean & SD
CVLT.sum <- d.CVLT %>% describe() %>% select(-vars) %>% rownames_to_column(var = "Variable") %>%
  filter(Variable != "BABS_ID*") %>% filter(Variable != "AGE AT SESSION")

kable(CVLT.sum, col.names = c("Variable","N","Mean","SD","Median","Trimmed Mean","Median Abs. Deviation","Min","Max","Range","Skew","Kurtosis","SE"),
      caption = "CVLT Summary Table") %>% kable_styling()
```

## Face-Name Associative Memory Examination (FNAME)

```{r FNAME, warning=FALSE, message=FALSE}
sub.IDs<- c("BABS005", "BABS006","BABS008", "BABS024", "BABS004", "BABS007", "BABS009", "BABS010", "BABS011", "BABS012", "BABS013", "BABS014", "BABS015", "BABS016", "BABS017", "BABS019", "BABS020", "BABS021", "BABS022", "BABS023", "BABS025","BABS026","BABS028","BABS029","BABS030","BABS031","BABS033","BABS035","BABS036","BABS037","BABS038","BABS040", "BABS042", "BABS043", "BABS044", "BABS045", "BABS046", "BABS049", "BABS051", "BABS053", "BABS055", "BABS056", "BABS057", "BABS058", "BABS059", "BABS060", "BABS061", "BABS062", "BABS066", "BABS067", "BABS069", "BABS070", "BABS071", "BABS072", "BABS073", "BABS074", "BABS075", "BABS076", "BABS077", "BABS079", "BABS080", "BABS081", "BABS082", "BABS083", "BABS084", "BABS085", "BABS086", "BABS087", "BABS088", "BABS089", "BABS090", "BABS091", "BABS092", "BABS093", "BABS094", "BABS095", "BABS096", "BABS097", "BABS098", "BABS099", "BABS100", "BABS101", "BABS102", "BABS104", "BABS105", "BABS106", "BABS107", "BABS108", "BABS110", "BABS111", "BABS112", "BABS113", "BABS114", "BABS115", "BABS116", "BABS117", "BABS118", "BABS119", "BABS121", "BABS122", "BABS124", "BABS125", "BABS126", "BABS128", "BABS129", "BABS130", "BABS131", "BABS132", "BABS133", "BABS134", "BABS135", "BABS136", "BABS138", "BABS139", "BABS141", "BABS142", "BABS143", "BABS145", "BABS146", "BABS147", "BABS148", "BABS150", "BABS151", "BABS152", "BABS154", "BABS155", "BABS157","BABS158", "BABS159", "BABS160", "BABS161", "BABS162", "BABS163", "BABS166", "BABS168", "BABS169", "BABS170", "BABS171", "BABS172", "BABS173", "BABS174", "BABS175", "BABS176", "BABS177", "BABS179", "BABS180", "BABS181", "BABS196", "BABS266", "BABS272", "BABS279", "BABS284")

Names <- c("fiona","kimberly","maria","courtney","Alice","julie","olivia","laura","miriam","kate","lucy",
           "paula","jane","stella","susan","isabelle")
Occupations <- c("teacher","dentist","detective","optometrist","editor","dancer","weaver","chef","pilot",
                 "nutritionist","electrician","lawyer","painter","scientist","architect","photographer")

#data frame
FNAME <- data_frame()
  for (sid in 1:length(sub.IDs)) { 
      FNAME.fname <- paste0(sess.path, sub.IDs[sid], "/Session_1/FNAME/");
      file <- dir(FNAME.fname, pattern = ".iqdat");
      setwd(FNAME.fname);
      file_data <- read_delim(file[1]) %>% select(subject, blockcode, trialcode, trialnum, starts_with("values")) %>%
        mutate(subject = as.character(subject));
FNAME <- bind_rows(FNAME, file_data);
  }

FRN.scores <- FNAME %>% group_by(subject) %>% filter(trialcode == "FRN") %>%
  mutate(FRN.list = str_split(as.character(values.response_FRN), ","),
    score.FRN = sapply(FRN.list, function(x) sum(x %in% Names))) %>% select(subject, score.FRN)

FRO.scores <- FNAME %>% group_by(subject) %>% filter(trialcode == "FRO") %>%
  mutate(FRO.list = str_split(as.character(values.response_FRO), ","),
    score.FRO = sapply(FRO.list, function(x) sum(x %in% Occupations))) %>% select(subject, score.FRO)

FRN30.scores <- FNAME %>% group_by(subject) %>% filter(trialcode == "FRN30") %>%
  mutate(FRN30.list = str_split(as.character(values.response_FRN30), ","),
    score.FRN30 = sapply(FRN30.list, function(x) sum(x %in% Names))) %>% select(subject, score.FRN30)

FRO30.scores <- FNAME %>% group_by(subject) %>% filter(trialcode == "FRO30") %>%
  mutate(FRO30.list = str_split(as.character(values.response_FRO30), ","),
    score.FRO30 = sapply(FRO30.list, function(x) sum(x %in% Occupations))) %>% select(subject, score.FRO30)

FNAME.clean <- FNAME %>% group_by(subject) %>%
  summarise(score.ILN = sum(values.correct_ILN, na.rm = T),
         score.ILO = sum(values.correct_ILO, na.rm = T),
         score.CRN = sum(values.correct_CRN, na.rm = T),
         score.CRO = sum(values.correct_CRO, na.rm = T),
         score.CRN30 = sum(values.correct_CRN30, na.rm = T),
         score.CRO30 = sum(values.correct_CRO30, na.rm = T)) %>%
  inner_join(FRN.scores) %>% inner_join(FRN30.scores) %>% inner_join(FRO.scores) %>% inner_join(FRO30.scores)
```

## Examining the correlational structure of the learning & memory tasks

```{r corr, warning=FALSE, message=FALSE}
#BABS subject IDs for analysis
sub.IDs <- c("BABS025","BABS026","BABS028","BABS029","BABS030","BABS031","BABS033","BABS035","BABS036","BABS037","BABS038","BABS040", "BABS042", "BABS043", "BABS044", "BABS045", "BABS046", "BABS049", "BABS051", "BABS053", "BABS055", "BABS056", "BABS057", "BABS058", "BABS059", "BABS060", "BABS061", "BABS062", "BABS066", "BABS067", "BABS069", "BABS070", "BABS071", "BABS072", "BABS073", "BABS074", "BABS075", "BABS076", "BABS077", "BABS079", "BABS080", "BABS081", "BABS082", "BABS083", "BABS084", "BABS085", "BABS086", "BABS087", "BABS088", "BABS089", "BABS090", "BABS091", "BABS092", "BABS093", "BABS094", "BABS095", "BABS096", "BABS097", "BABS098", "BABS099", "BABS100", "BABS101", "BABS102", "BABS104", "BABS105", "BABS106", "BABS107", "BABS108", "BABS110", "BABS111", "BABS112", "BABS113", "BABS114", "BABS115", "BABS116", "BABS117", "BABS118", "BABS119", "BABS121", "BABS122", "BABS124", "BABS125", "BABS126", "BABS128", "BABS129", "BABS130", "BABS131", "BABS132", "BABS133", "BABS134", "BABS135", "BABS136", "BABS138", "BABS139", "BABS141", "BABS142", "BABS143", "BABS145", "BABS146", "BABS147", "BABS148", "BABS150", "BABS151", "BABS152", "BABS154", "BABS155", "BABS157", "BABS158", "BABS159", "BABS160", "BABS161", "BABS162", "BABS163", "BABS166", "BABS168", "BABS169", "BABS170", "BABS171", "BABS172", "BABS173", "BABS174", "BABS175", "BABS176", "BABS177", "BABS179", "BABS180", "BABS181", "BABS196", "BABS266", "BABS272", "BABS279", "BABS284")
#merging data frames and cleaning data
d.DigSpan.F.trim <- d.DigSpan.F %>% filter(BABS_ID %in% sub.IDs) %>% mutate(Subject = parse_number(BABS_ID)) %>% select(-BABS_ID)
d.DigSpan.B.trim <- d.DigSpan.B %>% filter(BABS_ID %in% sub.IDs) %>% select(BABS_ID, DIGITSPAN_BACKWARD) %>% mutate(Subject = parse_number(BABS_ID)) %>% select(-BABS_ID)
d.digSpan.Trim <- d.DigSpan.F.trim %>% inner_join(d.DigSpan.B.trim)
d.KeepTrack.trim <- d.KeepTrack %>% filter(BABS_ID %in% sub.IDs) %>% select(BABS_ID, KEEPTRACK_TWOCATEGORIES_TOTAL, THREECATEGORIES_TOTAL, KEEPTRACK_FOURCATEGORIES_TOTAL) %>% mutate(Subject = parse_number(BABS_ID)) %>% select(-BABS_ID)
d.NBack.RT.wide<- Hard.NBack.RT.subj.sum %>% select(Subject, mean, Level) %>% pivot_wider(id_cols = Subject, names_from = Level,names_prefix = "NBack_RT_", values_from = mean)
d.NBack.ACC.wide<- Hard.NBack.ACC.subj.sum %>% select(Subject, mean, Level) %>% pivot_wider(id_cols = Subject, names_from = Level,names_prefix = "NBACK_ACC_", values_from = mean)
d.NBack.Trim <-d.NBack.ACC.wide %>% inner_join(d.NBack.RT.wide)
#creating data frame with all WM measures
d.WM <- d.digSpan.Trim %>% inner_join(d.NBack.Trim) %>% inner_join(d.KeepTrack.trim) %>% select(-Subject) %>%
  rename(DS_For = DIGITSPAN_FORWARD, DS_Back = DIGITSPAN_BACKWARD, KT_2 = KEEPTRACK_TWOCATEGORIES_TOTAL, KT_3 = THREECATEGORIES_TOTAL, KT_4 = KEEPTRACK_FOURCATEGORIES_TOTAL)
corr.WM <- correlation(d.WM)
corr.WM %>%
  summary(redundant = F) %>%
  plot() + ggplot2::theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
```