---
title: "BABS PSQI Summary"
author: "JLC"
date: "`r Sys.Date()`"
output: "html_document"
---

# PSQI Summary (from BABS Qualtrics data entry)

```{r setup, warning=FALSE, message=FALSE}
rm(list=ls())
#Import relevant packages
library(kableExtra); library(tabledown); library(tidyverse)

# Import data (will update path to Shared Drive once data entry is complete)
PSQI.path <- "~/Library/CloudStorage/Box-Box/BABS_Neuropsych/Data/PSQI.csv"
PSQI <-read.csv(PSQI.path, header = T) %>% select(BABS_ID, starts_with("PSQI")) %>%
  select(-c(PSQI_5j_text, PSQI_10e_desc)) %>%
  group_by(BABS_ID, PSQI_1, PSQI_3) %>% mutate_if(is.character, as.integer) %>% ungroup()
PSQI.output.path <- "~/Library/CloudStorage/Box-Box/BABS_Neuropsych/Data/PSQI_sum.csv"
```

## Optional: Participant IDs for summarization

```{r Sub_IDs, warning=FALSE, message=FALSE}
# Enter all participants that you would like to summarize here)
## This section can be commented out if you want to run all available participants
sub.IDs<- c("BABS005", "BABS006","BABS008", "BABS024", "BABS004", "BABS007", "BABS009", "BABS010", "BABS011", "BABS012",
            "BABS013", "BABS014", "BABS015", "BABS016", "BABS017", "BABS019", "BABS020", "BABS021", "BABS022", "BABS023",
            "BABS025","BABS026","BABS028","BABS029","BABS030","BABS031","BABS033","BABS035","BABS036","BABS037","BABS038",
            "BABS040", "BABS042", "BABS043", "BABS044", "BABS045", "BABS046", "BABS049", "BABS051", "BABS053", "BABS055",
            "BABS056", "BABS057", "BABS058", "BABS059", "BABS060", "BABS061", "BABS062", "BABS066", "BABS067", "BABS069",
            "BABS070", "BABS071", "BABS072", "BABS073", "BABS074", "BABS075", "BABS076", "BABS077", "BABS079", "BABS080",
            "BABS081", "BABS082", "BABS083", "BABS084", "BABS085", "BABS086", "BABS087", "BABS088", "BABS089", "BABS090",
            "BABS091", "BABS092", "BABS093", "BABS094", "BABS095", "BABS096", "BABS097", "BABS098", "BABS099", "BABS100",
            "BABS101", "BABS102", "BABS104", "BABS105", "BABS106", "BABS107", "BABS108", "BABS110", "BABS111", "BABS112",
            "BABS113", "BABS114", "BABS115", "BABS116", "BABS117", "BABS118", "BABS119", "BABS121", "BABS122", "BABS124",
            "BABS125", "BABS126", "BABS128", "BABS129", "BABS130", "BABS131", "BABS132", "BABS133", "BABS134", "BABS135",
            "BABS136", "BABS138", "BABS139", "BABS141", "BABS142", "BABS143", "BABS145", "BABS146", "BABS147", "BABS148",
            "BABS150", "BABS151", "BABS152", "BABS154", "BABS155", "BABS157","BABS158", "BABS159", "BABS160", "BABS161",
            "BABS162", "BABS163", "BABS166", "BABS168", "BABS169", "BABS170", "BABS171", "BABS172", "BABS173", "BABS174",
            "BABS175", "BABS176", "BABS177", "BABS179", "BABS180", "BABS181", "BABS196", "BABS266", "BABS272", "BABS279",
            "BABS284")
```

## Cleaning data frame for summary

```{r PSQI_clean, warning=FALSE, message=FALSE}
#Creating clean data frame for summary
PSQI.clean <- PSQI %>% pivot_longer(names_to = "facet", values_to = "response", -c(BABS_ID, PSQI_Session, PSQI_1, PSQI_2, PSQI_3, PSQI_4)) %>%
  separate_wider_delim(facet,"_", names = c(NA, "Item")) %>%
  mutate(Value = recode(response, "1" = 0, "2" = 1, "3" = 2, "4" = 3)) %>% select(-response) %>%
  pivot_wider(id_cols = c(BABS_ID, PSQI_Session, PSQI_1, PSQI_2, PSQI_3, PSQI_4), 
              names_from = "Item", names_prefix = "PSQI_", values_from = "Value")
PSQI.clean$PSQI_1 <- format(as.POSIXct(PSQI.clean$PSQI_1,format='%I:%M %p'),format="%H:%M")
PSQI.clean$PSQI_3 <- format(as.POSIXct(PSQI.clean$PSQI_3,format='%I:%M %p'),format="%H:%M")
#If you would like to create a summary using only a unique subset of participant IDs that you have supplied (in previous code chunk), you can simply add the following line of code to filter the raw data to the code above
# %>% filter(BABS_ID %in% sub.IDs)
```

## Calculating sleep variables for further summary

```{r PSQI_impute, warning=FALSE, message=FALSE}
#creating data frame that summarizes relevant sleep variables
PSQI.sleep.int <- PSQI.clean %>%
  mutate(PSQI_5j = replace_na(PSQI_5j, 0),
         Disturb_sum = PSQI_5a + PSQI_5b + PSQI_5c + PSQI_5e + PSQI_5f + PSQI_5g + PSQI_5h + PSQI_5i + PSQI_5j,
         Latency_recode = if_else(PSQI_2 < 16, 0, if_else(PSQI_2 < 31, 1, if_else(PSQI_2 < 61, 2, 3))),
         Latency_sum = Latency_recode + PSQI_5a,
         DayDysfun_sum = PSQI_8 + PSQI_9,
         Sleeptime = bedTime(PSQI_1, PSQI_3),
         tmphse = (PSQI_4/Sleeptime)*100)
```

## Creating PSQI-Specific Summary Scores with Imputed Values

```{r PSQI_sum, warning=FALSE, message=FALSE}
#data frame with summary items
PSQI.sum <- PSQI.sleep.int %>%
  mutate(PSQIDURAT = if_else(PSQI_4 > 6, 0, if_else(PSQI_4 > 5, 1, if_else(PSQI_4 > 4, 2, 3))),
         PSQIDISTB = if_else(Disturb_sum == 0, 0, if_else(Disturb_sum < 10, 1, if_else(Disturb_sum < 19, 2, 3))),
         PSQILATEN = if_else(Latency_sum == 0, 0, if_else(Latency_sum < 3, 1, if_else(Latency_sum < 5, 2, 3))),
         PSQIDAYDYS = if_else(DayDysfun_sum == 0, 0, if_else(DayDysfun_sum < 3, 1, if_else(DayDysfun_sum < 5, 2, 3))),
         PSQIHSE = if_else(tmphse > 84, 0, if_else(tmphse > 74, 1, if_else(tmphse > 64, 2, 3))),
         PSQISLPQUAL = PSQI_6,
         PSQIMEDS = PSQI_7,
         PSQI = PSQIDURAT + PSQIDISTB + PSQILATEN + PSQIDAYDYS + PSQIHSE + PSQISLPQUAL + PSQIMEDS) %>%
  select(BABS_ID, PSQI_Session, PSQI, PSQIDURAT, PSQIDISTB, PSQILATEN, PSQIDAYDYS, PSQIHSE, PSQISLPQUAL, PSQIMEDS)
#to save the results, un-comment the line below; file path & name can be adjusted in the first code chunk
#write.csv(PSQI.sum, file = PSQI.output.path, row.names = F)
```
